#!/bin/bash

set -e
set -x

export INSTALLDIR=${INSTALLDIR:-/home/wikifarm}
pwd=$(cd $(dirname $0)/. && pwd)
export SOURCEDIR=${SOURCEDIR:-$pwd}
export HOSTNAME="`hostname`"

perl -pe 's/{{(.*?)}}/$ENV{$1}/g' < $SOURCEDIR/wikifarm-apache2.conf.in > /tmp/wikifarm-apache2.conf.tmp

mkdir -p $INSTALLDIR
install $SOURCEDIR/awstats.00.conf $INSTALLDIR/etc/
install $SOURCEDIR/awstats.all.conf $INSTALLDIR/etc/
install /tmp/wikifarm-apache2.conf.tmp /etc/apache2/sites-available/wikifarm
install $SOURCEDIR/wikifarm-auth.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-update-config.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-update-stats.sh $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-backup.sh $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-log-split.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-create-wiki $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-php.ini /etc/php5/conf.d/
install $SOURCEDIR/{login,logout,index,claim-wiki-by-password}.php $INSTALLDIR/wikis/
install $SOURCEDIR/WikifarmDriver.php $INSTALLDIR/wikis/
install $SOURCEDIR/WikifarmPageMachine.php $INSTALLDIR/wikis/
install $SOURCEDIR/serverlogo.png $INSTALLDIR/wikis/
install $SOURCEDIR/favicon.ico $INSTALLDIR/wikis/

make -C $SOURCEDIR
install $SOURCEDIR/textile-2.0.0/classTextile.php $INSTALLDIR/wikis/
install $SOURCEDIR/help.textile $INSTALLDIR/wikis/
install $SOURCEDIR/adminhelp.textile $INSTALLDIR/wikis/
rsync -av $SOURCEDIR/help/ $INSTALLDIR/wikis/help/

mkdir -p $INSTALLDIR/wikis/js
install $SOURCEDIR/js/ajax-loader.gif $INSTALLDIR/wikis/js/
install $SOURCEDIR/js/jquery-1.4.2.min.js $INSTALLDIR/wikis/js/
install $SOURCEDIR/js/jquery-ui-1.8.4.custom.min.js $INSTALLDIR/wikis/js/
install $SOURCEDIR/js/wikifarm-ui.js $INSTALLDIR/wikis/js/
[ -d DataTables-1.7.1 ] || unzip DataTables-1.7.1.zip
rsync -av $SOURCEDIR/DataTables-1.7.1/media/ $INSTALLDIR/wikis/js/DataTables/

mkdir -p $INSTALLDIR/wikis/css
cp -r $SOURCEDIR/css/* $INSTALLDIR/wikis/css/
install $SOURCEDIR/style.css $INSTALLDIR/wikis/

install $SOURCEDIR/GeSHiHighlight.php /usr/share/mediawiki-extensions/
install $SOURCEDIR/WikifarmAuthPlugin.php /usr/share/mediawiki-extensions/
install $SOURCEDIR/SimpleTable.php /usr/share/mediawiki-extensions/

install /usr/share/doc/awstats/examples/awstats_buildstaticpages.pl $INSTALLDIR/etc/awstats_buildstaticpages.pl
perl -pi~ -e 's:2>&1:1>&2: if $.==372' $INSTALLDIR/etc/awstats_buildstaticpages.pl

mkdir -p $INSTALLDIR/db
php $SOURCEDIR/initialize_wikis_db.php
chown -R www-data:adm $INSTALLDIR/db
chmod -R o-rwx,g+rX $INSTALLDIR/db
chmod 750 $INSTALLDIR/db

$INSTALLDIR/etc/wikifarm-update-config.pl

sudo tee /etc/cron.d/wikifarm-update-stats <<EOF
30 4 * * * www-data $INSTALLDIR/etc/wikifarm-update-stats.sh
EOF
sudo tee /etc/cron.d/wikifarm-backup <<EOF
30 1 * * * www-data $INSTALLDIR/etc/wikifarm-backup.sh
EOF
sudo chmod a+x /var/log/apache2

a2ensite wikifarm
a2enmod ssl
a2enmod rewrite
mwenext WikifarmAuthPlugin.php
