#!/bin/bash

set -e
set -x

export INSTALLDIR=${INSTALLDIR:-/home/wikifarm}
pwd=$(cd $(dirname $0)/. && pwd)
export SOURCEDIR=${SOURCEDIR:-$pwd}
export HOSTNAME="`hostname`"

perl -pe 's/{{(.*?)}}/$ENV{$1}/g' < $SOURCEDIR/wikifarm-apache2.conf.in > /tmp/wikifarm-apache2.conf.tmp

mkdir -p $INSTALLDIR
install $SOURCEDIR/awstats.00.conf $INSTALLDIR/etc/
install $SOURCEDIR/awstats.all.conf $INSTALLDIR/etc/
install /tmp/wikifarm-apache2.conf.tmp /etc/apache2/sites-available/wikifarm
install $SOURCEDIR/wikifarm-auth.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-update-config.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-update-stats.sh $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-log-split.pl $INSTALLDIR/etc/
install $SOURCEDIR/wikifarm-php.ini /etc/php5/conf.d/
install $SOURCEDIR/{login,logout,index,claim-wiki-by-password}.php $INSTALLDIR/wikis/

install /usr/share/doc/awstats/examples/awstats_buildstaticpages.pl $INSTALLDIR/etc/awstats_buildstaticpages.pl
perl -pi~ -e 's:2>&1:1>&2: if $.==372' $INSTALLDIR/etc/awstats_buildstaticpages.pl

mkdir -p $INSTALLDIR/db
php $SOURCEDIR/initialize_wikis_db.php
chown -R www-data $INSTALLDIR/db
chmod -R go-rwx $INSTALLDIR/db
chmod 700 $INSTALLDIR/db

$INSTALLDIR/etc/wikifarm-update-config.pl

sudo tee /etc/cron.d/wikifarm-update-stats <<EOF
30 4 * * * www-data $INSTALLDIR/etc/wikifarm-update-stats.sh
EOF
sudo chmod a+x /var/log/apache2

a2ensite wikifarm
a2enmod ssl
a2enmod rewrite
