#!/bin/bash

set -e
set -x

export DESTDIR=${DESTDIR:-}
export INSTALLDIR=${INSTALLDIR:-/home/wikifarm}
export WWW=${WWW:-$INSTALLDIR/wikis}
export ETC=${ETC:-$INSTALLDIR/etc}
export DB=${DB:-$INSTALLDIR/db}
export SSL=${SSL:-$INSTALLDIR/etc/ssl}
pwd=$(cd $(dirname $0)/. && pwd)
export TREE=${TREE:-$pwd}
export SRC="$TREE/src"
export DEPS="$TREE/deps"

mkdir -p $DESTDIR$ETC
mkdir -p $DESTDIR/etc/php5/wikifarm
install $SRC/conf/awstats.00.conf $DESTDIR$ETC/
install $SRC/conf/awstats.all.conf $DESTDIR$ETC/
install $SRC/conf/wikifarm-apache2.conf.in $DESTDIR/etc/apache2/sites-available/wikifarm.conf
install $SRC/script/wikifarm-auth.pl $DESTDIR$ETC/
install $SRC/script/wikifarm-update-config.pl $DESTDIR$ETC/
install $SRC/script/wikifarm-update-stats.sh $DESTDIR$ETC/
install $SRC/script/wikifarm-backup.sh $DESTDIR$ETC/
install $SRC/script/wikifarm-log-split.pl $DESTDIR$ETC/
install $SRC/script/wikifarm-create-wiki $DESTDIR$ETC/
install $SRC/script/wikifarm-php.ini $DESTDIR/etc/php5/conf.d/
install $SRC/script/wikifarm-php.ini $DESTDIR/etc/php5/wikifarm/php.ini
install $SRC/script/wikifarm-sudo-enable $DESTDIR$ETC/
install $SRC/script/wikifarm-sudo-disable $DESTDIR$ETC/
install $SRC/script/wikifarm-template-save $DESTDIR$ETC/
install $SRC/script/make_admin_user.php $DESTDIR$ETC/
install $SRC/web/{login,logout,index,claim-wiki-by-password}.php $DESTDIR$WWW/
install $SRC/web/login-bg.gif $DESTDIR$WWW/
install $SRC/web/WikifarmDriver.php $DESTDIR$WWW/
install $SRC/web/WikifarmPageMachine.php $DESTDIR$WWW/
install $SRC/web/DefaultFarmSettings.php $DESTDIR$WWW/
install $SRC/web/serverlogo.png $DESTDIR$WWW/serverlogo.png.example
install $SRC/web/favicon.ico $DESTDIR$WWW/favicon.ico.example
install $SRC/conf/config.php.example $DESTDIR$ETC/
install $SRC/conf/mysql-utf8.cnf $DESTDIR$ETC/

make -C $TREE dist
install $TREE/dist/textile-2.0.0/classTextile.php $DESTDIR$WWW/
install $SRC/web/help.textile $DESTDIR$WWW/
install $SRC/web/adminhelp.textile $DESTDIR$WWW/
rsync -av $SRC/web/help/ $DESTDIR$WWW/help/

mkdir -p $DESTDIR$WWW/js
install $SRC/web/js/ajax-loader.gif $DESTDIR$WWW/js/
install $DEPS/jquery-1.4.2.min.js $DESTDIR$WWW/js/
install $DEPS/jquery-ui-1.8.4.custom.min.js $DESTDIR$WWW/js/
install $SRC/web/js/wikifarm-ui.js $DESTDIR$WWW/js/
if ! [ -d "$TREE/dist/DataTables-1.7.1" ]; then
    unzip "$TREE/deps/DataTables-1.7.1.zip" -d "$TREE/dist"
fi
rsync -av $TREE/dist/DataTables-1.7.1/media/ $DESTDIR$WWW/js/DataTables/

mkdir -p $DESTDIR$WWW/css
cp -r $SRC/web/css/* $DESTDIR$WWW/css/
install $SRC/web/style.css $DESTDIR$WWW/

for ext in $DEPS/SimpleTable.php $DEPS/GeSHiHighlight.php $SRC/WikifarmAuthPlugin.php
do
  install "$ext" "$DESTDIR$ETC/"
  extbase="$(basename "$ext")"
  ln -sf $ETC/$extbase "$DESTDIR"/etc/mediawiki-extensions/extensions-available/
done

install $SRC/script/initialize_wikis_db.php $DESTDIR$ETC/
install $SRC/script/setup $DESTDIR$ETC/
cat >$DESTDIR$ETC/env <<EOF
export DB="$DB"
export WWW="$WWW"
export ETC="$ETC"
export SSL="$SSL"
EOF

if [ -O $DESTDIR/etc/cron.d ]
then
  sudo=""
else
  sudo=sudo
fi

$sudo tee $DESTDIR/etc/cron.d/wikifarm-update-stats >/dev/null <<EOF
30 4 * * * www-data $ETC/wikifarm-update-stats.sh $ETC >>/tmp/wikifarm-stats.log 2>&1
EOF
$sudo tee $DESTDIR/etc/cron.d/wikifarm-backup >/dev/null <<EOF
30 1 * * * www-data $ETC/wikifarm-backup.sh $ETC >>/tmp/wikifarm-backup.log 2>&1
EOF
