#!/bin/bash

set -e

export ETC=$(cd $(dirname $0)/. && pwd)
. $ETC/env

if ! [[ -e "$ETC/site_secret" ]]; then
    (umask 077; head -c2000 /dev/urandom | sha256sum | head -c64 >"$ETC/site_secret.tmp")
    mv "$ETC/site_secret.tmp" "$ETC/site_secret"
    chown www-data "$ETC/site_secret"
fi

export HOSTNAME="`hostname`"
if fgrep -q '{{' /etc/apache2/sites-available/wikifarm.conf
then
  perl -pi~ -e 's/{{(.*?)}}/$ENV{$1}/g' /etc/apache2/sites-available/wikifarm.conf
fi

if [ -e /usr/share/awstats/tools/awstats_buildstaticpages.pl ]
then
  install /usr/share/awstats/tools/awstats_buildstaticpages.pl $ETC/awstats_buildstaticpages.pl
else
  install /usr/share/doc/awstats/examples/awstats_buildstaticpages.pl $ETC/awstats_buildstaticpages.pl
fi
perl -pi~ -e 's:2>&1:1>&2: if $.==372' $ETC/awstats_buildstaticpages.pl

if [ ! -e $DB/wikis.db ]
then
  mkdir -m 750 -p $DB
  php $ETC/initialize_wikis_db.php
else
  # upgrade existing tables, then give up on first "create table" failure (!)
  php $ETC/initialize_wikis_db.php || echo
fi
chown -R www-data:adm $DB
chmod -R o-rwx,g+rwX $DB

sudo chmod a+x /var/log/apache2

a2ensite wikifarm.conf
[ -e /etc/apache2/mods-enabled/rewrite.load ] || a2enmod rewrite
[ -e /etc/apache2/mods-enabled/auth_openid.load ] || a2enmod auth_openid

ln -s $ETC/WikifarmAuthPlugin.php /var/lib/mediawiki/extensions/

WIKIFARM_ETC="$ETC" $ETC/wikifarm-update-config.pl
$ETC/wikifarm-sudo-enable

if [ ! -e $WWW/mediawiki ]
then
  rsync -a --exclude AdminSettings.php /usr/share/mediawiki/ $WWW/mediawiki/
  rootuser=$(perl -ne 'do { print $1; exit 0 } if /^ *user *= *(.*)/' </etc/mysql/debian.cnf)
  rootpw=$(perl -ne 'do { print $1; exit 0 } if /^ *password *= *(.*)/' </etc/mysql/debian.cnf)
  cat >$WWW/mediawiki/AdminSettings.php <<EOF
<?php
\$wgDBadminuser = '$rootuser';
\$wgDBadminpassword = '$rootpw';
?>
EOF
fi

chown ubuntu:ubuntu $WWW
chown -R ubuntu:ubuntu $WWW/mediawiki
if [ ! -s $WWW/FarmSettings.php ]
then
  sudo -u ubuntu tee $WWW/FarmSettings.php >/dev/null <<EOF
<?php
?>
EOF
fi

if [ ! -e $WWW/00 ]
then
  $ETC/wikifarm-create-wiki 00 blank Wiki
fi

if apache2ctl configtest
then
  /etc/init.d/apache2 restart
fi

if [ ! -e /etc/mysql/conf.d/utf8.cnf ]
then
  cat <<EOF

*** I recommend installing $ETC/mysql-utf8.cnf into
*** /etc/mysql/conf.d/utf8.cnf and restarting mysql before creating
*** any databases.

EOF
fi
