#!/bin/bash

wikiid="$1"
wikishortname="$2"
wikirealname="$3"

exec 2>&1

set -e -o pipefail

if [ "$ETC_WIKIFARM" = "" ]
then
  . $(dirname $0)/env
else
  . $ETC_WIKIFARM/env
  set -x
fi

mkdir $WWW/$wikiid
cd $WWW/$wikiid
ln -s ../mediawiki/* ./
rm -f images LocalSettings.php
rm -f extensions.copy
mkdir images private private/stats
sudo chown -R www-data images private

if [ -e ../6tna.png ]
then
  rsync ../6tna.png ./
fi

if [ "$wikiid" = "00" ]
then
  chown www-data .
else
  rsync ../00/LocalSettings.php ./
  perl -pi~ -e "s/00/$wikiid/g; s/xxx/$wikishortname/g; s/^#// if /createaccount/;" $WWW/$wikiid/LocalSettings.php
fi

mysqlrootpw=$(echo '<?php require("'$WWW'/'$wikiid'/AdminSettings.php"); print $wgDBadminpassword; ?>' | php)
mysqlrootuser=$(echo '<?php require("'$WWW'/'$wikiid'/AdminSettings.php"); print $wgDBadminuser; ?>' | php)
mysqlrootuser=${mysqlrootuser:-root}

if [ "$wikiid" = "00" ]
then
  blanksql=$DB/emptydb.sql
  touch $blanksql
else
  blanksql=$DB/blankwiki.sql
  if [ ! -e $DB/blankwiki.sql ]
  then
    mysqldump -u "$mysqlrootuser" -p"$mysqlrootpw" -el wikidb00 | sudo sh -c "cat >$blanksql.tmp"
    mv $blanksql.tmp $blanksql
  fi
fi

mysql -u "$mysqlrootuser" -p"$mysqlrootpw" <<EOF
create database wikidb$wikiid;
use wikidb$wikiid;
source $blanksql
GRANT DELETE,INSERT,SELECT,UPDATE ON wikidb$wikiid.* TO 'wikiuser'@'%' IDENTIFIED BY 'wikipass';
GRANT DELETE,INSERT,SELECT,UPDATE ON wikidb$wikiid.* TO 'wikiuser'@localhost IDENTIFIED BY 'wikipass';
GRANT DELETE,INSERT,SELECT,UPDATE ON wikidb$wikiid.* TO 'wikiuser'@localhost.localdomain IDENTIFIED BY 'wikipass';
EOF

if [ "$wikiid" != "00" ]
then
 (
  cd $WWW/mediawiki/maintenance
  php update.php --quick --conf $WWW/$wikiid/LocalSettings.php --aconf ../AdminSettings.php
 )
fi

sudo chown -R mysql:adm /var/lib/mysql/
sudo chmod -R g+rX /var/lib/mysql/
sudo -E $ETC/wikifarm-update-config.pl
