#!/bin/sh

set -e
. $(dirname $0)/env

templatesettings=$WWW/00/LocalSettings.php
sudo mv ~ubuntu/00-LocalSettings.php $templatesettings
find $WWW/00 -user root -print0 | xargs -0 sudo chown ubuntu:ubuntu
sudo chown ubuntu:ubuntu $WWW/00
sudo chmod 644 $templatesettings

sudo tee -a $templatesettings <<'EOF'
$wgArticlePath = "/xxx/$1";
require_once(dirname(__FILE__)."/../DefaultFarmSettings.php");
require_once(dirname(__FILE__)."/../FarmSettings.php");
EOF
sudo perl -pi~ -e 's/^/#/ if /^define.*MW_INSTALL_PATH/' $templatesettings

echo 'Require all denied' | sudo tee $WWW/00/.htaccess
